CREATE TABLE requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity INTEGER,
    price DECIMAL(10, 2),
    product_request_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

